from base.jobs import CSVJob
from pygrametl.tables import Dimension, TypeOneSlowlyChangingDimension
from datetime import datetime


# class for customer dimension
class DimProgram(CSVJob):
    def configure(self):
        self.target_database = 'rightatschool_testdb'
        self.target_table = 'DimProgram'
        self.delimiter = ","
        self.quotechar = '"'
        # self.pick_file_to_process(folder = None, pattern = 'LDI_reject_claim_detail_06_05_2017.txt')
        # self.bucket_name = 'ldi.datafile.to-process'
        # self.bucket_folder = 'Rebate'
        self.source_table = ''
        self.source_database = ''
        self.file_name = 'sources/Right_Clubs_Electives_Extract.csv'

    def getColumnMapping(self):
        return [
            'Right Club & Elective Name',
            'Right Club & Elective Number',
            'Right Club & Elective External Number',
            'Right Club & Elective Type',
            'Season',
            'Term',
            'Right Club & Elective Status',
            'Department',
            'Right Club & Elective Category',
            'Right Club & Elective Other Category',
            'Catalog Description',
            'Expense GL Account',
            'Expense Offset GL Account',
            'Enable Deferred Revenue',
            'Deferred Revenue GL Account',
            'Deferred Revenue Frequency',
            'Tax Receipt Eligibility',
            'Budget Override Automatic Calculation',
            'Budget Income',
            'Budget Wage',
            'Budget Expense',
            'Qualifies for Commission',
            'Registration Fee Name',
            'Ignore Registration Fee for Trial Class',
            'Site Name',
            'Location Description',
            'Do not Reserve Facility',
            'Override Resource Closed Times',
            'Do not Create Meeting Dates',
            'Date Description',
            'Number of Meeting Dates',
            'Number of Calendar Weeks',
            'Gender',
            'Minimum Age',
            'Maximum Age',
            'Minimum Grade',
            'Maximum Grade',
            'Age Calc Date',
            'Maximum Age for Multi-person Fee',
            'Alternate Key Type',
            'Alternate Key Status',
            'Minimum Participants',
            'Maximum Participants',
            'Ignore Maximum Participants',
            'Maximum Enrollment per Receipt',
            'Maximum Online Enrollments',
            'Ignore Maximum Online Enrollments',
            'Trial Class Capacity',
            'Allow Trial Class',
            'Online Note - Right Club & Elective is Full',
            'User Notes',
            'Online Notes',
            'Receipt Notes',
            'No Internet Registration',
            'Require Initials Online',
            'Hide on Internet',
            'No quantity-based enrollment',
            'Use Pass or Fail',
            'Require withdraw reason',
            'Include in catalog',
            'Login not required for online enrollment',
            'Show system-generated price info online',
            'Show scholarship online',
            'Allow Waiting List',
            'Allow Selling Prerequisite Membership for Waiting List',
            'Allow Enroll with Deposit',
            'Flag as New Right Club & Elective on Internet',
            'Flag as New Right Club & Elective until Date',
            'Hold Roll-over Registration Seats',
            'Hold Roll-over Registration Seats For Days',
            'Hold Roll-over Registration Seats Until Date',
            'Allow Attendance Entry',
            'Allow Instructor to Edit Participant Skill Online',
            'Bypass Online Right Club & Elective Detail Page',
            'Check for Duplicate Enrollments',
            'Enrollment Notification Emails',
            'Withdrawal Notification Emails',
            'Supervisor',
            'Returning Participant Criteria',
            'Customize Warning',
            'Allow n/a Bookings',
            'Allow n/a Bookings Online ',
            'Maximum n/a Per Enrollee',
            'Minimum n/a Per Enrollee',
            'Allow Pre-Book n/a Only',
            'Allow Selecting Desired Booking Quantity Per Enrollee ',
            'Allow Selecting Desired Booking Quantity Per Enrollee Online ',
            'Prompt to Make Number of Bookings Equal to Actual If Different',
            'Automatically Make Number of Bookings Equal to Actual Bookings',
            'Minimum Advance Hours for Online Booking Changes',
            'Maximum n/a Duration ',
            'Minimum n/a Duration ',
            'Maximum Number of Enrollees Per Individual n/a',
            'Show All Scheduled n/a Dated on Receipt',
            'Enable n/a Dates Override ',
            'n/a First Date',
            'n/a Last Date',
            'n/a Days of Week',
            'n/a Week of Month',
            'n/a Beginning Time',
            'n/a Duration',
            'Maximum Number of Days in Availability Search Date Range',
            'Default Number of Months in Availability Search Date Range',
            'Booking Grid Interval',
            'Enforce Booking Pattern ',
            'Frequency',
            'Keep Same Day of The Week',
            'Keep Same Start and End Times',
            'Skills',
            'Prerequisite Groups1',
            'Donation Campaigns',
            'Checklist',
            'Parent Right Club & Elective',
            'Top Parent Right Club & Elective',
            'Sub-Right Club & Electives',
            'Merchandise',
            'Alias and Synonyms for Online Search',
            'Charge Name1',
            'Discount1',
            'Discount Order1',
            'Discount Group Number1',
            'Prefill Condition1',
            'Primary Fee1',
            'Charge Amount1',
            'Region1',
            'Fee Order1',
            'Customer Type1',
            'Description1',
            'G/L Account1A',
            'G/L Account Number1A',
            'System Account Package1',
            'Discountable 1',
            'Exclude from Payment Plans1',
            'Trial Class Fee1',
            'Pro-rate during refund1',
            'Pro-rate during enrollment1',
            'Charge Name2',
            'Discount2',
            'Discount Order2',
            'Discount Group Number2',
            'Prefill Condition2',
            'Primary Fee2',
            'Charge Amount2',
            'Region2',
            'Fee Order2',
            'Customer Type2',
            'Description2',
            'G/L Account2A',
            'G/L Account Number2A',
            'System Account Package2',
            'Discountable 2',
            'Exclude from Payment Plans2',
            'Trial Class Fee2',
            'Pro-rate during refund2',
            'Pro-rate during enrollment2',
            'Charge Name3',
            'Discount3',
            'Discount Order3',
            'Discount Group Number3',
            'Prefill Condition3',
            'Primary Fee3',
            'Charge Amount3',
            'Region3',
            'Fee Order3',
            'Customer Type3',
            'Description3',
            'G/L Account3A',
            'G/L Account Number3A',
            'System Account Package3',
            'Discountable 3',
            'Exclude from Payment Plans3',
            'Trial Class Fee3',
            'Pro-rate during refund3',
            'Pro-rate during enrollment3',
            'Charge Name4',
            'Discount4',
            'Discount Order4',
            'Discount Group Number4',
            'Prefill Condition4',
            'Primary Fee4',
            'Charge Amount4',
            'Region4',
            'Fee Order4',
            'Customer Type4',
            'Description4',
            'G/L Account4A',
            'G/L Account Number4A',
            'System Account Package4',
            'Discountable 4',
            'Exclude from Payment Plans4',
            'Trial Class Fee4',
            'Pro-rate during refund4',
            'Pro-rate during enrollment4',
            'Charge Name5',
            'Discount5',
            'Discount Order5',
            'Discount Group Number5',
            'Prefill Condition5',
            'Primary Fee5',
            'Charge Amount5',
            'Region5',
            'Fee Order5',
            'Customer Type5',
            'Description5',
            'G/L Account5A',
            'G/L Account Number5A',
            'System Account Package5',
            'Discountable 5',
            'Exclude from Payment Plans5',
            'Trial Class Fee5',
            'Pro-rate during refund5',
            'Pro-rate during enrollment5',
            'Charge Name6',
            'Discount6',
            'Discount Order6',
            'Discount Group Number6',
            'Prefill Condition6',
            'Primary Fee6',
            'Charge Amount6',
            'Region6',
            'Fee Order6',
            'Customer Type6',
            'Description6',
            'G/L Account6A',
            'G/L Account Number6A',
            'System Account Package6',
            'Discountable 6',
            'Exclude from Payment Plans6',
            'Trial Class Fee6',
            'Pro-rate during refund6',
            'Pro-rate during enrollment6',
            'Charge Name7',
            'Discount7',
            'Discount Order7',
            'Discount Group Number7',
            'Prefill Condition7',
            'Primary Fee7',
            'Charge Amount7',
            'Region7',
            'Fee Order7',
            'Customer Type7',
            'Description7',
            'G/L Account7A',
            'G/L Account Number7A',
            'System Account Package7',
            'Discountable 7',
            'Exclude from Payment Plans7',
            'Trial Class Fee7',
            'Pro-rate during refund7',
            'Pro-rate during enrollment7',
            'Charge Name8',
            'Discount8',
            'Discount Order8',
            'Discount Group Number8',
            'Prefill Condition8',
            'Primary Fee8',
            'Charge Amount8',
            'Region8',
            'Fee Order8',
            'Customer Type8',
            'Description8',
            'G/L Account8A',
            'G/L Account Number8A',
            'System Account Package8',
            'Discountable 8',
            'Exclude from Payment Plans8',
            'Trial Class Fee8',
            'Pro-rate during refund8',
            'Pro-rate during enrollment8',
            'Charge Name9',
            'Discount9',
            'Discount Order9',
            'Discount Group Number9',
            'Prefill Condition9',
            'Primary Fee9',
            'Charge Amount9',
            'Region9',
            'Fee Order9',
            'Customer Type9',
            'Description9',
            'G/L Account9A',
            'G/L Account Number9A',
            'System Account Package9',
            'Discountable 9',
            'Exclude from Payment Plans9',
            'Trial Class Fee9',
            'Pro-rate during refund9',
            'Pro-rate during enrollment9',
            'Charge Name10',
            'Discount10',
            'Discount Order10',
            'Discount Group Number10',
            'Prefill Condition10',
            'Primary Fee10',
            'Charge Amount10',
            'Region10',
            'Fee Order10',
            'Customer Type10',
            'Description10',
            'G/L Account10A',
            'G/L Account Number10A',
            'System Account Package10',
            'Discountable 10',
            'Exclude from Payment Plans10',
            'Trial Class Fee10',
            'Pro-rate during refund10',
            'Pro-rate during enrollment10',
            'Charge Name11',
            'Discount11',
            'Discount Order11',
            'Discount Group Number11',
            'Prefill Condition11',
            'Primary Fee11',
            'Charge Amount11',
            'Region11',
            'Fee Order11',
            'Customer Type11',
            'Description11',
            'G/L Account11A',
            'G/L Account Number11A',
            'System Account Package11',
            'Discountable 11',
            'Exclude from Payment Plans11',
            'Trial Class Fee11',
            'Pro-rate during refund11',
            'Pro-rate during enrollment11',
            'Charge Name12',
            'Discount12',
            'Discount Order12',
            'Discount Group Number12',
            'Prefill Condition12',
            'Primary Fee12',
            'Charge Amount12',
            'Region12',
            'Fee Order12',
            'Customer Type12',
            'Description12',
            'G/L Account12A',
            'G/L Account Number12A',
            'System Account Package12',
            'Discountable 12',
            'Exclude from Payment Plans12',
            'Trial Class Fee12',
            'Pro-rate during refund12',
            'Pro-rate during enrollment12',
            'Charge Name13',
            'Discount13',
            'Discount Order13',
            'Discount Group Number13',
            'Prefill Condition13',
            'Primary Fee13',
            'Charge Amount13',
            'Region13',
            'Fee Order13',
            'Customer Type13',
            'Description13',
            'G/L Account13A',
            'G/L Account Number13A',
            'System Account Package13',
            'Discountable 13',
            'Exclude from Payment Plans13',
            'Trial Class Fee13',
            'Pro-rate during refund13',
            'Pro-rate during enrollment13',
            'Charge Name14',
            'Discount14',
            'Discount Order14',
            'Discount Group Number14',
            'Prefill Condition14',
            'Primary Fee14',
            'Charge Amount14',
            'Region14',
            'Fee Order14',
            'Customer Type14',
            'Description14',
            'G/L Account14A',
            'G/L Account Number14A',
            'System Account Package14',
            'Discountable 14',
            'Exclude from Payment Plans14',
            'Trial Class Fee14',
            'Pro-rate during refund14',
            'Pro-rate during enrollment14',
            'Charge Name15',
            'Discount15',
            'Discount Order15',
            'Discount Group Number15',
            'Prefill Condition15',
            'Primary Fee15',
            'Charge Amount15',
            'Region15',
            'Fee Order15',
            'Customer Type15',
            'Description15',
            'G/L Account15A',
            'G/L Account Number15A',
            'System Account Package15',
            'Discountable 15',
            'Exclude from Payment Plans15',
            'Trial Class Fee15',
            'Pro-rate during refund15',
            'Pro-rate during enrollment15',
            'Charge Name16',
            'Discount16',
            'Discount Order16',
            'Discount Group Number16',
            'Prefill Condition16',
            'Primary Fee16',
            'Charge Amount16',
            'Region16',
            'Fee Order16',
            'Customer Type16',
            'Description16',
            'G/L Account16A',
            'G/L Account Number16A',
            'System Account Package16',
            'Discountable 16',
            'Exclude from Payment Plans16',
            'Trial Class Fee16',
            'Pro-rate during refund16',
            'Pro-rate during enrollment16',
            'Charge Name17',
            'Discount17',
            'Discount Order17',
            'Discount Group Number17',
            'Prefill Condition17',
            'Primary Fee17',
            'Charge Amount17',
            'Region17',
            'Fee Order17',
            'Customer Type17',
            'Description17',
            'G/L Account17A',
            'G/L Account Number17A',
            'System Account Package17',
            'Discountable 17',
            'Exclude from Payment Plans17',
            'Trial Class Fee17',
            'Pro-rate during refund17',
            'Pro-rate during enrollment17',
            'Charge Name18',
            'Discount18',
            'Discount Order18',
            'Discount Group Number18',
            'Prefill Condition18',
            'Primary Fee18',
            'Charge Amount18',
            'Region18',
            'Fee Order18',
            'Customer Type18',
            'Description18',
            'G/L Account18A',
            'G/L Account Number18A',
            'System Account Package18',
            'Discountable 18',
            'Exclude from Payment Plans18',
            'Trial Class Fee18',
            'Pro-rate during refund18',
            'Pro-rate during enrollment18',
            'Charge Name19',
            'Discount19',
            'Discount Order19',
            'Discount Group Number19',
            'Prefill Condition19',
            'Primary Fee19',
            'Charge Amount19',
            'Region19',
            'Fee Order19',
            'Customer Type19',
            'Description19',
            'G/L Account19A',
            'G/L Account Number19A',
            'System Account Package19',
            'Discountable 19',
            'Exclude from Payment Plans19',
            'Trial Class Fee19',
            'Pro-rate during refund19',
            'Pro-rate during enrollment19',
            'Charge Name20',
            'Discount20',
            'Discount Order20',
            'Discount Group Number20',
            'Prefill Condition20',
            'Primary Fee20',
            'Charge Amount20',
            'Region20',
            'Fee Order20',
            'Customer Type20',
            'Description20',
            'G/L Account20A',
            'G/L Account Number20A',
            'System Account Package20',
            'Discountable 20',
            'Exclude from Payment Plans20',
            'Trial Class Fee20',
            'Pro-rate during refund20',
            'Pro-rate during enrollment20',
            'Charge Name21',
            'Discount21',
            'Discount Order21',
            'Discount Group Number21',
            'Prefill Condition21',
            'Primary Fee21',
            'Charge Amount21',
            'Region21',
            'Fee Order21',
            'Customer Type21',
            'Description21',
            'G/L Account21A',
            'G/L Account Number21A',
            'System Account Package21',
            'Discountable 21',
            'Exclude from Payment Plans21',
            'Trial Class Fee21',
            'Pro-rate during refund21',
            'Pro-rate during enrollment21',
            'Charge Name22',
            'Discount22',
            'Discount Order22',
            'Discount Group Number22',
            'Prefill Condition22',
            'Primary Fee22',
            'Charge Amount22',
            'Region22',
            'Fee Order22',
            'Customer Type22',
            'Description22',
            'G/L Account22A',
            'G/L Account Number22A',
            'System Account Package22',
            'Discountable 22',
            'Exclude from Payment Plans22',
            'Trial Class Fee22',
            'Pro-rate during refund22',
            'Pro-rate during enrollment22',
            'Charge Name23',
            'Discount23',
            'Discount Order23',
            'Discount Group Number23',
            'Prefill Condition23',
            'Primary Fee23',
            'Charge Amount23',
            'Region23',
            'Fee Order23',
            'Customer Type23',
            'Description23',
            'G/L Account23A',
            'G/L Account Number23A',
            'System Account Package23',
            'Discountable 23',
            'Exclude from Payment Plans23',
            'Trial Class Fee23',
            'Pro-rate during refund23',
            'Pro-rate during enrollment23',
            'Charge Name24',
            'Discount24',
            'Discount Order24',
            'Discount Group Number24',
            'Prefill Condition24',
            'Primary Fee24',
            'Charge Amount24',
            'Region24',
            'Fee Order24',
            'Customer Type24',
            'Description24',
            'G/L Account24A',
            'G/L Account Number24A',
            'System Account Package24',
            'Discountable 24',
            'Exclude from Payment Plans24',
            'Trial Class Fee24',
            'Pro-rate during refund24',
            'Pro-rate during enrollment24',
            'Charge Name25',
            'Discount25',
            'Discount Order25',
            'Discount Group Number25',
            'Prefill Condition25',
            'Primary Fee25',
            'Charge Amount25',
            'Region25',
            'Fee Order25',
            'Customer Type25',
            'Description25',
            'G/L Account25A',
            'G/L Account Number25A',
            'System Account Package25',
            'Discountable 25',
            'Exclude from Payment Plans25',
            'Trial Class Fee25',
            'Pro-rate during refund25',
            'Pro-rate during enrollment25',
            'Charge Name26',
            'Discount26',
            'Discount Order26',
            'Discount Group Number26',
            'Prefill Condition26',
            'Primary Fee26',
            'Charge Amount26',
            'Region26',
            'Fee Order26',
            'Customer Type26',
            'Description26',
            'G/L Account26A',
            'G/L Account Number26A',
            'System Account Package26',
            'Discountable 26',
            'Exclude from Payment Plans26',
            'Trial Class Fee26',
            'Pro-rate during refund26',
            'Pro-rate during enrollment26',
            'Charge Name27',
            'Discount27',
            'Discount Order27',
            'Discount Group Number27',
            'Prefill Condition27',
            'Primary Fee27',
            'Charge Amount27',
            'Region27',
            'Fee Order27',
            'Customer Type27',
            'Description27',
            'G/L Account27A',
            'G/L Account Number27A',
            'System Account Package27',
            'Discountable 27',
            'Exclude from Payment Plans27',
            'Trial Class Fee27',
            'Pro-rate during refund27',
            'Pro-rate during enrollment27',
            'Charge Name28',
            'Discount28',
            'Discount Order28',
            'Discount Group Number28',
            'Prefill Condition28',
            'Primary Fee28',
            'Charge Amount28',
            'Region28',
            'Fee Order28',
            'Customer Type28',
            'Description28',
            'G/L Account28A',
            'G/L Account Number28A',
            'System Account Package28',
            'Discountable 28',
            'Exclude from Payment Plans28',
            'Trial Class Fee28',
            'Pro-rate during refund28',
            'Pro-rate during enrollment28',
            'Charge Name29',
            'Discount29',
            'Discount Order29',
            'Discount Group Number29',
            'Prefill Condition29',
            'Primary Fee29',
            'Charge Amount29',
            'Region29',
            'Fee Order29',
            'Customer Type29',
            'Description29',
            'G/L Account29A',
            'G/L Account Number29A',
            'System Account Package29',
            'Discountable 29',
            'Exclude from Payment Plans29',
            'Trial Class Fee29',
            'Pro-rate during refund29',
            'Pro-rate during enrollment29',
            'Charge Name30',
            'Discount30',
            'Discount Order30',
            'Discount Group Number30',
            'Prefill Condition30',
            'Primary Fee30',
            'Charge Amount30',
            'Region30',
            'Fee Order30',
            'Customer Type30',
            'Description30',
            'G/L Account30A',
            'G/L Account Number30A',
            'System Account Package30',
            'Discountable 30',
            'Exclude from Payment Plans30',
            'Trial Class Fee30',
            'Pro-rate during refund30',
            'Pro-rate during enrollment30',
            'Charge Name31',
            'Discount31',
            'Discount Order31',
            'Discount Group Number31',
            'Prefill Condition31',
            'Primary Fee31',
            'Charge Amount31',
            'Region31',
            'Fee Order31',
            'Customer Type31',
            'Description31',
            'G/L Account31A',
            'G/L Account Number31A',
            'System Account Package31',
            'Discountable 31',
            'Exclude from Payment Plans31',
            'Trial Class Fee31',
            'Pro-rate during refund31',
            'Pro-rate during enrollment31',
            'Charge Name32',
            'Discount32',
            'Discount Order32',
            'Discount Group Number32',
            'Prefill Condition32',
            'Primary Fee32',
            'Charge Amount32',
            'Region32',
            'Fee Order32',
            'Customer Type32',
            'Description32',
            'G/L Account32A',
            'G/L Account Number32A',
            'System Account Package32',
            'Discountable 32',
            'Exclude from Payment Plans32',
            'Trial Class Fee32',
            'Pro-rate during refund32',
            'Pro-rate during enrollment32',
            'Charge Name33',
            'Discount33',
            'Discount Order33',
            'Discount Group Number33',
            'Prefill Condition33',
            'Primary Fee33',
            'Charge Amount33',
            'Region33',
            'Fee Order33',
            'Customer Type33',
            'Description33',
            'G/L Account33A',
            'G/L Account Number33A',
            'System Account Package33',
            'Discountable 33',
            'Exclude from Payment Plans33',
            'Trial Class Fee33',
            'Pro-rate during refund33',
            'Pro-rate during enrollment33',
            'Charge Name34',
            'Discount34',
            'Discount Order34',
            'Discount Group Number34',
            'Prefill Condition34',
            'Primary Fee34',
            'Charge Amount34',
            'Region34',
            'Fee Order34',
            'Customer Type34',
            'Description34',
            'G/L Account34A',
            'G/L Account Number34A',
            'System Account Package34',
            'Discountable 34',
            'Exclude from Payment Plans34',
            'Trial Class Fee34',
            'Pro-rate during refund34',
            'Pro-rate during enrollment34',
            'Charge Name35',
            'Discount35',
            'Discount Order35',
            'Discount Group Number35',
            'Prefill Condition35',
            'Primary Fee35',
            'Charge Amount35',
            'Region35',
            'Fee Order35',
            'Customer Type35',
            'Description35',
            'G/L Account35A',
            'G/L Account Number35A',
            'System Account Package35',
            'Discountable 35',
            'Exclude from Payment Plans35',
            'Trial Class Fee35',
            'Pro-rate during refund35',
            'Pro-rate during enrollment35',
            'Charge Name36',
            'Discount36',
            'Discount Order36',
            'Discount Group Number36',
            'Prefill Condition36',
            'Primary Fee36',
            'Charge Amount36',
            'Region36',
            'Fee Order36',
            'Customer Type36',
            'Description36',
            'G/L Account36A',
            'G/L Account Number36A',
            'System Account Package36',
            'Discountable 36',
            'Exclude from Payment Plans36',
            'Trial Class Fee36',
            'Pro-rate during refund36',
            'Pro-rate during enrollment36',
            'Charge Name37',
            'Discount37',
            'Discount Order37',
            'Discount Group Number37',
            'Prefill Condition37',
            'Primary Fee37',
            'Charge Amount37',
            'Region37',
            'Fee Order37',
            'Customer Type37',
            'Description37',
            'G/L Account37A',
            'G/L Account Number37A',
            'System Account Package37',
            'Discountable 37',
            'Exclude from Payment Plans37',
            'Trial Class Fee37',
            'Pro-rate during refund37',
            'Pro-rate during enrollment37',
            'Charge Name38',
            'Discount38',
            'Discount Order38',
            'Discount Group Number38',
            'Prefill Condition38',
            'Primary Fee38',
            'Charge Amount38',
            'Region38',
            'Fee Order38',
            'Customer Type38',
            'Description38',
            'G/L Account38A',
            'G/L Account Number38A',
            'System Account Package38',
            'Discountable 38',
            'Exclude from Payment Plans38',
            'Trial Class Fee38',
            'Pro-rate during refund38',
            'Pro-rate during enrollment38',
            'Charge Name39',
            'Discount39',
            'Discount Order39',
            'Discount Group Number39',
            'Prefill Condition39',
            'Primary Fee39',
            'Charge Amount39',
            'Region39',
            'Fee Order39',
            'Customer Type39',
            'Description39',
            'G/L Account39A',
            'G/L Account Number39A',
            'System Account Package39',
            'Discountable 39',
            'Exclude from Payment Plans39',
            'Trial Class Fee39',
            'Pro-rate during refund39',
            'Pro-rate during enrollment39',
            'Charge Name40',
            'Discount40',
            'Discount Order40',
            'Discount Group Number40',
            'Prefill Condition40',
            'Primary Fee40',
            'Charge Amount40',
            'Region40',
            'Fee Order40',
            'Customer Type40',
            'Description40',
            'G/L Account40A',
            'G/L Account Number40A',
            'System Account Package40',
            'Discountable 40',
            'Exclude from Payment Plans40',
            'Trial Class Fee40',
            'Pro-rate during refund40',
            'Pro-rate during enrollment40',
            'Charge Name41',
            'Discount41',
            'Discount Order41',
            'Discount Group Number41',
            'Prefill Condition41',
            'Primary Fee41',
            'Charge Amount41',
            'Region41',
            'Fee Order41',
            'Customer Type41',
            'Description41',
            'G/L Account41A',
            'G/L Account Number41A',
            'System Account Package41',
            'Discountable 41',
            'Exclude from Payment Plans41',
            'Trial Class Fee41',
            'Pro-rate during refund41',
            'Pro-rate during enrollment41',
            'Charge Name42',
            'Discount42',
            'Discount Order42',
            'Discount Group Number42',
            'Prefill Condition42',
            'Primary Fee42',
            'Charge Amount42',
            'Region42',
            'Fee Order42',
            'Customer Type42',
            'Description42',
            'G/L Account42A',
            'G/L Account Number42A',
            'System Account Package42',
            'Discountable 42',
            'Exclude from Payment Plans42',
            'Trial Class Fee42',
            'Pro-rate during refund42',
            'Pro-rate during enrollment42',
            'Charge Name43',
            'Discount43',
            'Discount Order43',
            'Discount Group Number43',
            'Prefill Condition43',
            'Primary Fee43',
            'Charge Amount43',
            'Region43',
            'Fee Order43',
            'Customer Type43',
            'Description43',
            'G/L Account43A',
            'G/L Account Number43A',
            'System Account Package43',
            'Discountable 43',
            'Exclude from Payment Plans43',
            'Trial Class Fee43',
            'Pro-rate during refund43',
            'Pro-rate during enrollment43',
            'Charge Name44',
            'Discount44',
            'Discount Order44',
            'Discount Group Number44',
            'Prefill Condition44',
            'Primary Fee44',
            'Charge Amount44',
            'Region44',
            'Fee Order44',
            'Customer Type44',
            'Description44',
            'G/L Account44A',
            'G/L Account Number44A',
            'System Account Package44',
            'Discountable 44',
            'Exclude from Payment Plans44',
            'Trial Class Fee44',
            'Pro-rate during refund44',
            'Pro-rate during enrollment44',
            'Global Discount Name1',
            'Global Discount Order1',
            'Global Discount Group Number1',
            'Global Discount Amount/Percent1',
            'Global Discount Retired1',
            'Global Discount Name2',
            'Global Discount Order2',
            'Global Discount Group Number2',
            'Global Discount Amount/Percent2',
            'Global Discount Retired2',
            'Global Discount Name3',
            'Global Discount Order3',
            'Global Discount Group Number3',
            'Global Discount Amount/Percent3',
            'Global Discount Retired3',
            'Global Discount Name4',
            'Global Discount Order4',
            'Global Discount Group Number4',
            'Global Discount Amount/Percent4',
            'Global Discount Retired4',
            'Global Discount Name5',
            'Global Discount Order5',
            'Global Discount Group Number5',
            'Global Discount Amount/Percent5',
            'Global Discount Retired5',
            'Global Discount Name6',
            'Global Discount Order6',
            'Global Discount Group Number6',
            'Global Discount Amount/Percent6',
            'Global Discount Retired6',
            'Global Discount Name7',
            'Global Discount Order7',
            'Global Discount Group Number7',
            'Global Discount Amount/Percent7',
            'Global Discount Retired7',
            'Global Discount Name8',
            'Global Discount Order8',
            'Global Discount Group Number8',
            'Global Discount Amount/Percent8',
            'Global Discount Retired8',
            'Refund Charge',
            'Refund Charge Description',
            'Refund Charge G/L Account',
            'Refund Charge Fixed Amount',
            'Refund Charge Percentage of Charges',
            'Refund Charge Percentage of Amount Paid',
            'Payment Plan Name1',
            'Default Payment Plan1',
            'Automatically Charge Payments When Due1',
            'Allow Online1',
            'Initial Payment1',
            'Payment Distribution for Balance1',
            'Payment Schedule Type1',
            'Enable Payment Plan Surcharge1',
            'Qualified Customers and Companies1',
            'Priority Priority First Day/Time in Person',
            'Priority Priority First Day/Time in Person for Non-residents',
            'Priority Priority First Day/Time in Person for Members',
            'Priority Priority Last Day/Time in Person',
            'Priority Priority First Day/Time on Internet',
            'Priority Priority First Day/Time on Internet for Non-residents',
            'Priority Priority First Day/Time on Internet for Members',
            'Priority Priority Last Day/Time on Internet',
            'First Day/Time in Person1',
            'First Day/Time in Person for Non-residents1',
            'First Day/Time in Person for Members1',
            'Last Day/Time in Person1',
            'First Day/Time on Internet1',
            'First Day/Time on Internet for Non-residents1',
            'First Day/Time on Internet for Members1',
            'Last Day/Time on Internet1',
            'Default Pattern Name',
            'Default Facilities',
            'Default Preparation Code',
            'Default Event Notes',
            'Default First Date',
            'Default Last Date',
            'Default Week of Month',
            'Default Days of Week, Start Time, and Duration',
            'Question Name1',
            'Required1',
            'Question Name2',
            'Required2',
            'Question Name3',
            'Required3',
            'Question Name4',
            'Required4',
            'Question Name5',
            'Required5',
            'Question Name6',
            'Required6',
            'Question Name7',
            'Required7',
            'Question Name8',
            'Required8',
            'Question Name9',
            'Required9',
            'Question Name10',
            'Required10',
            'Question Name11',
            'Required11',
            'Question Name12',
            'Required12',
            'Question Name13',
            'Required13',
            'Question Name14',
            'Required14',
            'Instructor Name1',
            'Instructor Role1',
            'Instructor Payrate Code1',
            'Instructor Start Date1',
            'Instructor End Date1',
            'Instructor Email Registration Notification1',
            'Instructor Show Online1',
            'Instructor Exclude From Normal Payroll1',
            'Instructor Total Up-front Preparation Time1',
            'Instructor Preparation Time Per Session1']

    def getTarget(self):
        # print('target')
        return self.target_connection.cursor()

    # Override the following method if the data needs to be transformed before insertion
    def prepareRow(self, row):
        # print('prepare')
        myfields = [
            'Right Club & Elective Number',
            'Right Club & Elective Name',
            'Right Club & Elective Type',
            'Season',
            'Right Club & Elective Category',
            'Right Club & Elective Other Category',
            'Catalog Description',
            'Registration Fee Name',
            'Site Name',
            'Location Description',
            'Date Description',
            'Number of Meeting Dates',
            'Number of Calendar Weeks',
            'Minimum Age',
            'Maximum Age',
            'Allow Waiting List',
            'Enrollment Notification Emails',
            'Withdrawal Notification Emails',
            'Supervisor']
        # print(myfields)
        newrow = {}
        for f in myfields:
            newrow[f] = row[f] if f in row else None
        # newrow = { f:row[f] for f in set(myfields) }
        print('new:', newrow)

        return newrow

    # Override the following method if the data needs to be transformed before insertion
    def insertRow(self, cursor, row):
        # print('prep:',row)
        # print(row['RecType'])
        # target.insert(row)
        # print("Inserting row:")
        # row.keys()
        if row["Right Club & Elective Number"] != "Right Club & Elective Number":
            databasevalues = [
                'RightClubElectiveNumber',
                'RightClubElectiveName',
                'RightClubElectiveType',
                'Season',
                'RightClubElectiveCategory',
                'RightClubElectiveOtherCategory',
                'CatalogDescription',
                'RegistrationFeeName',
                'SiteName',
                'LocationDescription',
                'DateDescription',
                'NumberofMeetingDates',
                'NumberofCalendarWeeks',
                'MinimumAge',
                'MaximumAge',
                'AllowWaitingList',
                'EnrollmentNotificationEmails',
                'WithdrawalNotificationEmails',
                'Supervisor' ]
            name_placeholders = ", ".join(["`{}`".format(s) for s in databasevalues])
            value_placeholders = ", ".join(['%s'] * len(row))
            sql = "INSERT INTO `{}` ({}) VALUES ({}) ".format(self.target_table, name_placeholders,value_placeholders)
            cursor.execute(sql, tuple(row.values()))
            self.target_connection.commit()

    def close(self):
        """Here we should archive the file instead"""
        # self.active_cursor.close()
